package bunch.api;

enum Key {

     CALLBACK_OBJECT_REF,
     CALLBACK_OBJECT_FREQ,

     RUNTIME,
     MQEVALUATIONS,

     CLUSTER_LEVEL,
     MQVALUE,
     CLUSTER_DEPTH,
     NUMBER_CLUSTERS,

     TOTAL_CLUSTER_LEVELS,
     RESULT_CLUSTER_OBJS,
     SA_NEIGHBORS_TAKEN,
     MEDIAN_LEVEL_GRAPH,

     PR_PRECISION_VALUE,
     PR_RECALL_VALUE,

     MQCALC_RESULT_VALUE,

     ERROR_HASHTABLE,
     WARNING_HASHTABLE,
    REFLEXIVE_EDGE_COUNT,

    OMNIPRESENT_CLIENT,
    OMNIPRESENT_SUPPLIER,
    OMNIPRESENT_CENTRAL,
    LIBRARY_MODULE

}
